# Brightpearl API configuration
# For more information, see the
# Brightpearl API documentation here
#   http://www.brightpearl.com/developer/latest/
# and more specifically here
#   http://www.brightpearl.com/developer/latest/concept/uri-syntax.html
---
id: mumoc
email: mumo.crls@gmail.com
password: 220502Camubrightpearl
distribution_centre: use
api_version: 2.0.0
